import type { PresentationConfig } from "./index.js"

/** Zod-free fallback used when presentation negotiation fails. / presentation取得失敗時に使うZod非依存fallbackです。 */
export const defaultPresentationValue = {
  version: 1,
  locale: "ja-JP",
  brand: {
    name: "Notion Reader",
    shortName: "Reader",
    eyebrow: "Personal reference",
    tagline: "Your Notion, shaped for reading.",
  },
  theme: {
    colorScheme: "dark",
    colors: {
      background: "#0b0d10",
      panel: "#11151b",
      panelAlt: "#171c24",
      line: "#2a313c",
      text: "#edf2f7",
      muted: "#98a2b3",
      accent: "#d8ff5f",
      accentSecondary: "#7cecff",
      danger: "#ff7a90",
    },
  },
  messages: {
    navHome: "Home",
    navSearch: "Search",
    navLogout: "Logout",
    loginEyebrow: "Private library",
    loginTitle: "Notion Reader",
    loginPrompt: "Reader password を入力してください。",
    passwordLabel: "Password",
    loginButton: "Login",
    loginPending: "Signing in…",
    homeEyebrow: "Personal reference",
    homeTitle: "Your Notion, shaped for reading.",
    homeDescription: "許可された Database を read-only で表示します。",
    librariesHeading: "Libraries",
    databaseEyebrow: "Database",
    templatesSuffix: "templates",
    recentHeading: "Recently read",
    clearRecent: "Clear",
    emptyRecent: "最近読んだ記事はありません。",
    libraryEyebrow: "Library",
    backHome: "← Home",
    backLibrary: "← Library",
    loadMore: "Load more",
    loading: "Loading…",
    emptyLibrary: "記事がありません。",
    searchEyebrow: "Registered databases only",
    searchTitle: "Title & property search",
    searchDescription: "本文全文検索ではありません。",
    searchPlaceholder: "Title",
    searchButton: "Search",
    emptySearch: "該当する記事はありません。",
    templateLabel: "Template",
    demoTitle: "Explore the Reader demo",
    demoDescription: "公開用のダミーデータだけを使用する静的デモです。",
    demoStart: "デモを開始",
    demoBadge: "Demo data",
    demoExit: "Exit demo",
  },
  articleHeaders: {
    simple: {
      name: "Simple",
      renderer: "field-grid",
      title: { placement: "content", alignment: "center" },
      tone: "panel",
      density: "comfortable",
      fields: [
        {
          variable: "mainClass",
          label: "Main-class",
          width: "third",
          emphasis: "normal",
          showIcon: true,
        },
        {
          variable: "subClass",
          label: "Sub-class",
          width: "third",
          emphasis: "normal",
          showIcon: true,
        },
        {
          variable: "codeName",
          label: "Code name",
          width: "third",
          emphasis: "strong",
          showIcon: true,
        },
      ],
    },
    "compact-emblem": {
      name: "Compact Emblem",
      renderer: "compact-emblem",
      title: { placement: "content", alignment: "center" },
      tone: "panel",
      density: "compact",
      emblemVariable: "mainClass",
      headlineVariable: "codeName",
      headlineLabel: "Code name",
      headlineFallback: "title",
      fields: [
        {
          variable: "mainClass",
          label: "Main-class",
          width: "half",
          emphasis: "normal",
          showIcon: true,
        },
        {
          variable: "subClass",
          label: "Sub-class",
          width: "half",
          emphasis: "normal",
          showIcon: true,
        },
      ],
    },
  },
} satisfies PresentationConfig
