import { randomUUID } from "node:crypto"
import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import {
  DemoDatasetSchema,
  DemoManifestSchema,
  type DemoDataset,
} from "@foundation-like-notion/contracts"
import yaml from "js-yaml"
import sharp from "sharp"
import type { SourceAsset } from "./adapters/content-adapter.js"
import { DEMO_EXPORT_LIMITS, DemoExportError, type DemoAssetWriter } from "./demo-exporter.js"

const NOTION_ID_PATTERN =
  /(?:\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b|\b[0-9a-f]{32}\b)/i
const PRIVATE_MARKERS = [
  "api.notion.com",
  "@notionhq/client",
  "NOTION_TOKEN",
  "READER_PASSWORD_HASH",
  "sourceDataSourceId",
  "titlePropertyId",
  "propertyId",
  "X-Amz-Credential",
  "X-Amz-Signature",
  "X-Goog-Signature",
]

export type DemoDirectoryOperations = Readonly<{
  copy: (source: string, destination: string) => Promise<void>
  move: (source: string, destination: string) => Promise<void>
  remove: (target: string) => Promise<void>
}>

const nodeDirectoryOperations: DemoDirectoryOperations = {
  copy: async (source, destination) => {
    await cp(source, destination, { recursive: true, errorOnExist: true })
  },
  move: rename,
  remove: async (target) => {
    await rm(target, { recursive: true, force: true })
  },
}

function assertWithin(parent: string, child: string): void {
  const relative = path.relative(path.resolve(parent), path.resolve(child))
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new DemoExportError("unsafe_output_path")
  }
}

function significant(values: readonly string[]): readonly string[] {
  return [...new Set(values.filter((value) => value.length >= 8))]
}

/**
 * Reject private identifiers and signed endpoints without printing their values.
 * 非公開IDと署名付きendpointを、値を出力せず拒否します。
 *
 * Args:
 *   content: Bytes to inspect.
 *   privateValues: Exact local values that must not appear.
 *   pathLabel: Safe relative path used only for diagnostics.
 *
 * Raises:
 *   DemoExportError: The content contains a private marker, source identifier, or private value.
 */
export function assertPublicBytes(
  content: Uint8Array,
  privateValues: readonly string[],
  pathLabel: string,
): void {
  const text = Buffer.from(content).toString("latin1")
  if (PRIVATE_MARKERS.some((marker) => text.includes(marker))) {
    throw new DemoExportError("private_marker_detected", pathLabel)
  }
  if (NOTION_ID_PATTERN.test(text)) {
    throw new DemoExportError("source_identifier_detected", pathLabel)
  }
  if (significant(privateValues).some((value) => text.includes(value))) {
    throw new DemoExportError("private_value_detected", pathLabel)
  }
}

async function downloadAsset(source: SourceAsset): Promise<Buffer> {
  let parsed: URL
  try {
    parsed = new URL(source.url)
  } catch {
    throw new DemoExportError("asset_url_rejected")
  }
  if (parsed.protocol !== "https:") throw new DemoExportError("asset_url_rejected")
  const response = await fetch(parsed, {
    ...(source.fetchProfile === "notion-icon"
      ? {
          headers: {
            Accept: "image/svg+xml,image/*,*/*;q=0.8",
            "User-Agent": "Foundation-Like-Notion/0.1",
          },
        }
      : {}),
    redirect: "follow",
    signal: AbortSignal.timeout(30_000),
  })
  if (!response.ok || !response.body) throw new DemoExportError("asset_unavailable")
  try {
    if (new URL(response.url).protocol !== "https:") throw new DemoExportError("asset_url_rejected")
  } catch (error) {
    if (error instanceof DemoExportError) throw error
    throw new DemoExportError("asset_url_rejected")
  }
  const declared = Number(response.headers.get("content-length"))
  if (Number.isFinite(declared) && declared > DEMO_EXPORT_LIMITS.assetBytes) {
    throw new DemoExportError("asset_limit_exceeded")
  }
  const reader = response.body.getReader()
  const chunks: Uint8Array[] = []
  let bytes = 0
  while (true) {
    const result = await reader.read()
    if (result.done) break
    bytes += result.value.byteLength
    if (bytes > DEMO_EXPORT_LIMITS.assetBytes) {
      await reader.cancel()
      throw new DemoExportError("asset_limit_exceeded")
    }
    chunks.push(result.value)
  }
  return Buffer.concat(
    chunks.map((chunk) => Buffer.from(chunk)),
    bytes,
  )
}

/**
 * Create an asset writer that materializes safe static files below one candidate directory.
 * 1つの候補directory配下へ安全な静的assetを書き出すwriterを作成します。
 *
 * Args:
 *   publishedRoot: Candidate directory that owns all generated assets.
 *   privateValues: Exact local values that must not appear in generated bytes.
 *
 * Returns:
 *   An asset writer that downloads, sanitizes, validates, and stores one asset.
 */
export function createDemoAssetWriter(
  publishedRoot: string,
  privateValues: readonly string[],
): DemoAssetWriter {
  const assetRoot = path.join(publishedRoot, "assets")
  let downloadedBytes = 0
  return async (source, publicAssetId) => {
    const downloaded = await downloadAsset(source)
    downloadedBytes += downloaded.byteLength
    if (downloadedBytes > DEMO_EXPORT_LIMITS.totalAssetBytes) {
      throw new DemoExportError("total_asset_limit_exceeded")
    }
    const image = source.kind === "image"
    let output: Buffer
    let extension: string
    try {
      output = image
        ? await sharp(downloaded, { animated: true, limitInputPixels: 100_000_000 })
            .rotate()
            .webp({ quality: 90, effort: 4 })
            .toBuffer()
        : downloaded
      extension = image ? ".webp" : ".bin"
    } catch {
      throw new DemoExportError("asset_decode_failed")
    }
    if (output.byteLength > DEMO_EXPORT_LIMITS.assetBytes) {
      throw new DemoExportError("asset_limit_exceeded")
    }
    const relativePath = `assets/${publicAssetId}${extension}`
    const absolutePath = path.join(publishedRoot, relativePath)
    assertWithin(assetRoot, absolutePath)
    assertPublicBytes(output, privateValues, relativePath)
    await mkdir(path.dirname(absolutePath), { recursive: true })
    await writeFile(absolutePath, output)
    return { relativePath, bytes: output.byteLength }
  }
}

function dumpYaml(value: unknown): string {
  return yaml.dump(value, {
    forceQuotes: true,
    lineWidth: 100,
    noCompatMode: true,
    noRefs: true,
    quotingType: '"',
    sortKeys: false,
  })
}

/**
 * Write a complete validated dataset into an isolated candidate directory.
 * 検証済みdataset全体を、隔離された候補directoryへ書き込みます。
 */
export async function writeDemoCandidate(
  publishedRoot: string,
  dataset: DemoDataset,
  privateValues: readonly string[],
): Promise<void> {
  const articleRoot = path.join(publishedRoot, "articles")
  await mkdir(articleRoot, { recursive: true })
  const articleFiles: string[] = []
  for (const article of dataset.articles) {
    const relativePath = `articles/${article.id}.yaml`
    const content = dumpYaml(article)
    assertPublicBytes(Buffer.from(content), privateValues, relativePath)
    await writeFile(path.join(publishedRoot, relativePath), content, "utf8")
    articleFiles.push(relativePath)
  }
  const manifest = {
    presentation: dataset.presentation,
    databases: dataset.databases,
    articleFiles,
    assets: dataset.assets,
  }
  const content = dumpYaml(manifest)
  assertPublicBytes(Buffer.from(content), privateValues, "demo.yaml")
  await writeFile(path.join(publishedRoot, "demo.yaml"), content, "utf8")
  await readDemoCandidate(publishedRoot)
}

/**
 * Read and validate a candidate exactly as the Vite demo build will.
 * Viteのdemo buildと同じ方法で候補を読み込み、検証します。
 */
export async function readDemoCandidate(publishedRoot: string): Promise<DemoDataset> {
  const manifest = DemoManifestSchema.parse(
    yaml.load(await readFile(path.join(publishedRoot, "demo.yaml"), "utf8")),
  )
  const articles = await Promise.all(
    manifest.articleFiles.map(async (relativePath) => {
      const absolutePath = path.resolve(publishedRoot, relativePath)
      assertWithin(publishedRoot, absolutePath)
      return yaml.load(await readFile(absolutePath, "utf8"))
    }),
  )
  const dataset = DemoDatasetSchema.parse({
    presentation: manifest.presentation,
    databases: manifest.databases,
    articles,
    assets: manifest.assets,
  })
  for (const relativePath of Object.values(dataset.assets)) {
    const absolutePath = path.resolve(publishedRoot, relativePath)
    assertWithin(publishedRoot, absolutePath)
    await readFile(absolutePath)
  }
  return dataset
}

async function nestedFiles(directory: string): Promise<readonly string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const groups = await Promise.all(
    entries.map(async (entry) => {
      const absolutePath = path.join(directory, entry.name)
      return entry.isDirectory() ? nestedFiles(absolutePath) : [absolutePath]
    }),
  )
  return groups.flat()
}

/**
 * Scan the complete source snapshot, including binary downloads, for private values.
 * binary downloadを含むsource snapshot全体に非公開値がないか検査します。
 */
export async function validateDemoCandidatePrivacy(
  publishedRoot: string,
  privateValues: readonly string[],
): Promise<void> {
  await readDemoCandidate(publishedRoot)
  for (const filePath of await nestedFiles(publishedRoot)) {
    assertWithin(publishedRoot, filePath)
    assertPublicBytes(
      await readFile(filePath),
      privateValues,
      path.relative(publishedRoot, filePath),
    )
  }
}

/**
 * Replace the tracked published snapshot with one already validated candidate.
 * 検証済み候補で追跡対象snapshotをrollback可能なdirectory交換により置換します。
 */
export async function applyDemoCandidate(
  repositoryRoot: string,
  candidatePublishedRoot: string,
  operations: DemoDirectoryOperations = nodeDirectoryOperations,
): Promise<void> {
  await readDemoCandidate(candidatePublishedRoot)
  const demoRoot = path.join(repositoryRoot, "demo")
  const destination = path.join(demoRoot, "published")
  const nonce = `${process.pid}-${randomUUID()}`
  const staged = path.join(demoRoot, `.published-next-${nonce}`)
  const backup = path.join(demoRoot, `.published-backup-${nonce}`)
  assertWithin(demoRoot, destination)
  assertWithin(demoRoot, staged)
  assertWithin(demoRoot, backup)
  await operations.copy(candidatePublishedRoot, staged)
  let backedUp = false
  try {
    try {
      await operations.move(destination, backup)
      backedUp = true
    } catch (error) {
      if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error
    }
    await operations.move(staged, destination)
  } catch (error) {
    await operations.remove(staged)
    if (backedUp) {
      await operations.remove(destination)
      await operations.move(backup, destination)
    }
    throw error
  }
  if (backedUp) await operations.remove(backup)
}

export async function resetCandidate(candidateRoot: string, repositoryRoot: string): Promise<void> {
  const exportRoot = path.join(repositoryRoot, ".data", "demo-export")
  assertWithin(exportRoot, candidateRoot)
  await rm(candidateRoot, { recursive: true, force: true })
  await mkdir(candidateRoot, { recursive: true })
}
